api2doc: 
  title: 金丰供应链系统API接口文档

server:
  port: 8090

logging:
  config: classpath:log4j2.xml

spring:
    application:
        name: sdms
    #pringboot上传文件大小的配置
    http.multipart.maxFileSize: 10Mb  
    http.multipart.maxRequestSize: 50Mb
    
    #Druid数据源配置,https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
    datasource: 
        #JDBC配置druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sdms_db?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&useSSL=false
        username: scdp
        password: ccz@dbt888
        
        #druid连接池配置
        druid: 
            filters: config,stat,wall
            initial-size: 3
            min-idle: 3
            max-active: 30
            validation-query: select 'x'
            #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
            pool-prepared-statements: false
            #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            test-on-borrow: false
            #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
            test-on-return: false
            #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
            test-while-idle: true
            #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            time-between-eviction-runs-millis: 60000
            
            #durid监控配置
            stat-view-servlet.login-username: admin
            stat-view-servlet.login-password: admin
            #白名单
            stat-view-servlet.allow: 127.0.0.1
            #黑名单
            stat-view-servlet.deny: 192.168.1.73
            filter.stat.merge-sql: true
            filter.stat.log-slow-sql: true
            filter.stat.slow-sql-millis: 10000
            web-stat-filter.exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        
        # 配置日志输出
        filter:
          slf4j:
            enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false

## 该配置节点为独立的节点，容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.honest.sdms.*.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql